// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (message_id, file_name, file_size, mime_type, storage_path, thumbnail_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message_id, file_name, file_size, mime_type, storage_path, thumbnail_path, created_at
`

type CreateAttachmentParams struct {
	MessageID     int64       `json:"message_id"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	MimeType      string      `json:"mime_type"`
	StoragePath   string      `json:"storage_path"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.StoragePath,
		arg.ThumbnailPath,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachmentsByMessage = `-- name: DeleteAttachmentsByMessage :exec
DELETE FROM attachments WHERE message_id = $1
`

func (q *Queries) DeleteAttachmentsByMessage(ctx context.Context, messageID int64) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByMessage, messageID)
	return err
}

const getAttachmentAccessContext = `-- name: GetAttachmentAccessContext :one
SELECT
  a.id,
  a.message_id,
  a.file_name,
  a.file_size,
  a.mime_type,
  a.storage_path,
  a.thumbnail_path,
  a.created_at,
  m.chat_id
FROM attachments a
JOIN messages m ON m.id = a.message_id
WHERE a.id = $1
`

type GetAttachmentAccessContextRow struct {
	ID            int64              `json:"id"`
	MessageID     int64              `json:"message_id"`
	FileName      string             `json:"file_name"`
	FileSize      int64              `json:"file_size"`
	MimeType      string             `json:"mime_type"`
	StoragePath   string             `json:"storage_path"`
	ThumbnailPath pgtype.Text        `json:"thumbnail_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ChatID        int64              `json:"chat_id"`
}

func (q *Queries) GetAttachmentAccessContext(ctx context.Context, id int64) (GetAttachmentAccessContextRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentAccessContext, id)
	var i GetAttachmentAccessContextRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.CreatedAt,
		&i.ChatID,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, message_id, file_name, file_size, mime_type, storage_path, thumbnail_path, created_at
FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, message_id, file_name, file_size, mime_type, storage_path, thumbnail_path, created_at
FROM attachments WHERE message_id = $1
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByMessageIDs = `-- name: ListAttachmentsByMessageIDs :many
SELECT
  id,
  message_id,
  file_name,
  file_size,
  mime_type,
  storage_path,
  thumbnail_path,
  created_at
FROM attachments
WHERE message_id = ANY($1::bigint[])
ORDER BY message_id, id
`

func (q *Queries) ListAttachmentsByMessageIDs(ctx context.Context, dollar_1 []int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
