// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (chat_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddChatMemberParams struct {
	ChatID int64       `json:"chat_id"`
	UserID int64       `json:"user_id"`
	Role   pgtype.Text `json:"role"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.Exec(ctx, addChatMember, arg.ChatID, arg.UserID, arg.Role)
	return err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (type, name, avatar_url, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, type, name, avatar_url, created_by, created_at
`

type CreateChatParams struct {
	Type      string      `json:"type"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.Type,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedBy,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findDirectChat = `-- name: FindDirectChat :one
SELECT cm1.chat_id
FROM chat_members cm1
JOIN chat_members cm2 ON cm1.chat_id = cm2.chat_id
JOIN chats c ON c.id = cm1.chat_id
WHERE cm1.user_id = $1 AND cm2.user_id = $2 AND c.type = 'direct'
`

type FindDirectChatParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) FindDirectChat(ctx context.Context, arg FindDirectChatParams) (int64, error) {
	row := q.db.QueryRow(ctx, findDirectChat, arg.UserID, arg.UserID_2)
	var chat_id int64
	err := row.Scan(&chat_id)
	return chat_id, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, type, name, avatar_url, created_by, created_at
FROM chats WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(
    SELECT 1 FROM chat_members WHERE chat_id = $1 AND user_id = $2
) AS is_member
`

type IsChatMemberParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listChatMembers = `-- name: ListChatMembers :many
SELECT u.id, u.username, u.display_name, u.avatar_url, u.last_seen_at, cm.role, cm.joined_at
FROM chat_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.chat_id = $1
ORDER BY cm.joined_at
`

type ListChatMembersRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	Role        pgtype.Text        `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListChatMembers(ctx context.Context, chatID int64) ([]ListChatMembersRow, error) {
	rows, err := q.db.Query(ctx, listChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatMembersRow{}
	for rows.Next() {
		var i ListChatMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LastSeenAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsByUser = `-- name: ListChatsByUser :many
SELECT c.id, c.type, c.name, c.avatar_url, c.created_by, c.created_at,
       lm.id AS last_message_id, lm.content AS last_message_content,
       lm.sender_id AS last_message_sender_id, lm.created_at AS last_message_at
FROM chat_members cm
JOIN chats c ON c.id = cm.chat_id
LEFT JOIN messages lm ON lm.id = (
    SELECT id FROM messages WHERE chat_id = c.id ORDER BY created_at DESC LIMIT 1
)
WHERE cm.user_id = $1
ORDER BY COALESCE(lm.created_at, c.created_at) DESC
`

type ListChatsByUserRow struct {
	ID                  int64              `json:"id"`
	Type                string             `json:"type"`
	Name                pgtype.Text        `json:"name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	CreatedBy           pgtype.Int8        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LastMessageID       pgtype.Int8        `json:"last_message_id"`
	LastMessageContent  pgtype.Text        `json:"last_message_content"`
	LastMessageSenderID pgtype.Int8        `json:"last_message_sender_id"`
	LastMessageAt       pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) ListChatsByUser(ctx context.Context, userID int64) ([]ListChatsByUserRow, error) {
	rows, err := q.db.Query(ctx, listChatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatsByUserRow{}
	for rows.Next() {
		var i ListChatsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageSenderID,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChatMember = `-- name: RemoveChatMember :exec
DELETE FROM chat_members WHERE chat_id = $1 AND user_id = $2
`

type RemoveChatMemberParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) error {
	_, err := q.db.Exec(ctx, removeChatMember, arg.ChatID, arg.UserID)
	return err
}

const updateChat = `-- name: UpdateChat :one
UPDATE chats
SET name = COALESCE($2, name),
    avatar_url = COALESCE($3, avatar_url)
WHERE id = $1
RETURNING id, type, name, avatar_url, created_by, created_at
`

type UpdateChatParams struct {
	ID        int64       `json:"id"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChat, arg.ID, arg.Name, arg.AvatarUrl)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
