// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, created_by, expires_at)
VALUES ($1, $2, $3)
RETURNING id, code, created_by, used_by, expires_at, used_at, created_at
`

type CreateInviteParams struct {
	Code      string             `json:"code"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.Code, arg.CreatedBy, arg.ExpiresAt)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, created_by, used_by, expires_at, used_at, created_at
FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, code, created_by, used_by, expires_at, used_at, created_at
FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedBy,
			&i.UsedBy,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites SET used_by = $1, used_at = now() WHERE id = $2
`

type MarkInviteUsedParams struct {
	UsedBy pgtype.Int8 `json:"used_by"`
	ID     int64       `json:"id"`
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteUsed, arg.UsedBy, arg.ID)
	return err
}
