// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_reads.sql

package dbq

import (
	"context"
)

const getMessageRead = `-- name: GetMessageRead :one
SELECT chat_id, user_id, last_read_msg_id, read_at
FROM message_reads
WHERE chat_id = $1 AND user_id = $2
`

type GetMessageReadParams struct {
	ChatID int64 `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetMessageRead(ctx context.Context, arg GetMessageReadParams) (MessageRead, error) {
	row := q.db.QueryRow(ctx, getMessageRead, arg.ChatID, arg.UserID)
	var i MessageRead
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.LastReadMsgID,
		&i.ReadAt,
	)
	return i, err
}

const listMessageReadsByChat = `-- name: ListMessageReadsByChat :many
SELECT chat_id, user_id, last_read_msg_id, read_at
FROM message_reads
WHERE chat_id = $1
`

func (q *Queries) ListMessageReadsByChat(ctx context.Context, chatID int64) ([]MessageRead, error) {
	rows, err := q.db.Query(ctx, listMessageReadsByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageRead{}
	for rows.Next() {
		var i MessageRead
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.LastReadMsgID,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessageRead = `-- name: UpsertMessageRead :exec
INSERT INTO message_reads (chat_id, user_id, last_read_msg_id, read_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (chat_id, user_id) DO UPDATE
SET last_read_msg_id = GREATEST(message_reads.last_read_msg_id, EXCLUDED.last_read_msg_id),
    read_at = now()
`

type UpsertMessageReadParams struct {
	ChatID        int64 `json:"chat_id"`
	UserID        int64 `json:"user_id"`
	LastReadMsgID int64 `json:"last_read_msg_id"`
}

func (q *Queries) UpsertMessageRead(ctx context.Context, arg UpsertMessageReadParams) error {
	_, err := q.db.Exec(ctx, upsertMessageRead, arg.ChatID, arg.UserID, arg.LastReadMsgID)
	return err
}
