// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content, reply_to_id)
VALUES ($1, $2, $3, $4)
RETURNING id, chat_id, sender_id, content, reply_to_id, created_at, updated_at
`

type CreateMessageParams struct {
	ChatID    int64       `json:"chat_id"`
	SenderID  int64       `json:"sender_id"`
	Content   pgtype.Text `json:"content"`
	ReplyToID pgtype.Int8 `json:"reply_to_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatID,
		arg.SenderID,
		arg.Content,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT m.id, m.chat_id, m.sender_id, m.content, m.reply_to_id, m.created_at, m.updated_at,
       u.username AS sender_username, u.display_name AS sender_display_name
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID                int64              `json:"id"`
	ChatID            int64              `json:"chat_id"`
	SenderID          int64              `json:"sender_id"`
	Content           pgtype.Text        `json:"content"`
	ReplyToID         pgtype.Int8        `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SenderUsername    string             `json:"sender_username"`
	SenderDisplayName string             `json:"sender_display_name"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SenderUsername,
		&i.SenderDisplayName,
	)
	return i, err
}

const listMessagesByChatBefore = `-- name: ListMessagesByChatBefore :many
SELECT m.id, m.chat_id, m.sender_id, m.content, m.reply_to_id, m.created_at, m.updated_at,
       u.username AS sender_username, u.display_name AS sender_display_name
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.chat_id = $1
  AND (m.created_at, m.id) < (
      SELECT msg.created_at, msg.id FROM messages msg WHERE msg.id = $2
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListMessagesByChatBeforeParams struct {
	ChatID int64 `json:"chat_id"`
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
}

type ListMessagesByChatBeforeRow struct {
	ID                int64              `json:"id"`
	ChatID            int64              `json:"chat_id"`
	SenderID          int64              `json:"sender_id"`
	Content           pgtype.Text        `json:"content"`
	ReplyToID         pgtype.Int8        `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SenderUsername    string             `json:"sender_username"`
	SenderDisplayName string             `json:"sender_display_name"`
}

func (q *Queries) ListMessagesByChatBefore(ctx context.Context, arg ListMessagesByChatBeforeParams) ([]ListMessagesByChatBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByChatBefore, arg.ChatID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByChatBeforeRow{}
	for rows.Next() {
		var i ListMessagesByChatBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderUsername,
			&i.SenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChatLatest = `-- name: ListMessagesByChatLatest :many
SELECT m.id, m.chat_id, m.sender_id, m.content, m.reply_to_id, m.created_at, m.updated_at,
       u.username AS sender_username, u.display_name AS sender_display_name
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.chat_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2
`

type ListMessagesByChatLatestParams struct {
	ChatID int64 `json:"chat_id"`
	Limit  int32 `json:"limit"`
}

type ListMessagesByChatLatestRow struct {
	ID                int64              `json:"id"`
	ChatID            int64              `json:"chat_id"`
	SenderID          int64              `json:"sender_id"`
	Content           pgtype.Text        `json:"content"`
	ReplyToID         pgtype.Int8        `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SenderUsername    string             `json:"sender_username"`
	SenderDisplayName string             `json:"sender_display_name"`
}

func (q *Queries) ListMessagesByChatLatest(ctx context.Context, arg ListMessagesByChatLatestParams) ([]ListMessagesByChatLatestRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByChatLatest, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByChatLatestRow{}
	for rows.Next() {
		var i ListMessagesByChatLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderUsername,
			&i.SenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages SET content = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, id)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages
SET content = $2, updated_at = now()
WHERE id = $1
RETURNING id, chat_id, sender_id, content, reply_to_id, created_at, updated_at
`

type UpdateMessageContentParams struct {
	ID      int64       `json:"id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
