// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID            int64              `json:"id"`
	MessageID     int64              `json:"message_id"`
	FileName      string             `json:"file_name"`
	FileSize      int64              `json:"file_size"`
	MimeType      string             `json:"mime_type"`
	StoragePath   string             `json:"storage_path"`
	ThumbnailPath pgtype.Text        `json:"thumbnail_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Chat struct {
	ID        int64              `json:"id"`
	Type      string             `json:"type"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatMember struct {
	ChatID   int64              `json:"chat_id"`
	UserID   int64              `json:"user_id"`
	Role     pgtype.Text        `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Invite struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	UsedBy    pgtype.Int8        `json:"used_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID        int64              `json:"id"`
	ChatID    int64              `json:"chat_id"`
	SenderID  int64              `json:"sender_id"`
	Content   pgtype.Text        `json:"content"`
	ReplyToID pgtype.Int8        `json:"reply_to_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MessageRead struct {
	ChatID        int64              `json:"chat_id"`
	UserID        int64              `json:"user_id"`
	LastReadMsgID int64              `json:"last_read_msg_id"`
	ReadAt        pgtype.Timestamptz `json:"read_at"`
}

type PushSubscription struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	P256dhKey string             `json:"p256dh_key"`
	AuthKey   string             `json:"auth_key"`
	UserAgent pgtype.Text        `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	IsAdmin      pgtype.Bool        `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
}
