// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (user_id, endpoint, p256dh_key, auth_key, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE
SET p256dh_key = EXCLUDED.p256dh_key,
    auth_key = EXCLUDED.auth_key,
    user_agent = EXCLUDED.user_agent
RETURNING id, user_id, endpoint, p256dh_key, auth_key, user_agent, created_at
`

type CreatePushSubscriptionParams struct {
	UserID    int64       `json:"user_id"`
	Endpoint  string      `json:"endpoint"`
	P256dhKey string      `json:"p256dh_key"`
	AuthKey   string      `json:"auth_key"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, createPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dhKey,
		&i.AuthKey,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   int64  `json:"user_id"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh_key, auth_key, user_agent, created_at
FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID int64) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
