// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChatMember(ctx context.Context, arg AddChatMemberParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAttachmentsByMessage(ctx context.Context, messageID int64) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteInvite(ctx context.Context, id int64) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUserRefreshTokens(ctx context.Context, userID pgtype.Int8) error
	FindDirectChat(ctx context.Context, arg FindDirectChatParams) (int64, error)
	GetAttachmentAccessContext(ctx context.Context, id int64) (GetAttachmentAccessContextRow, error)
	GetAttachmentByID(ctx context.Context, id int64) (Attachment, error)
	GetChatByID(ctx context.Context, id int64) (Chat, error)
	GetInviteByCode(ctx context.Context, code string) (Invite, error)
	GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error)
	GetMessageRead(ctx context.Context, arg GetMessageReadParams) (MessageRead, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error)
	ListAttachmentsByMessage(ctx context.Context, messageID int64) ([]Attachment, error)
	ListAttachmentsByMessageIDs(ctx context.Context, dollar_1 []int64) ([]Attachment, error)
	ListChatMembers(ctx context.Context, chatID int64) ([]ListChatMembersRow, error)
	ListChatsByUser(ctx context.Context, userID int64) ([]ListChatsByUserRow, error)
	ListInvites(ctx context.Context) ([]Invite, error)
	ListMessageReadsByChat(ctx context.Context, chatID int64) ([]MessageRead, error)
	ListMessagesByChatBefore(ctx context.Context, arg ListMessagesByChatBeforeParams) ([]ListMessagesByChatBeforeRow, error)
	ListMessagesByChatLatest(ctx context.Context, arg ListMessagesByChatLatestParams) ([]ListMessagesByChatLatestRow, error)
	ListPushSubscriptionsByUser(ctx context.Context, userID int64) ([]PushSubscription, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error
	RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) error
	SoftDeleteMessage(ctx context.Context, id int64) error
	UpdateChat(ctx context.Context, arg UpdateChatParams) (Chat, error)
	UpdateLastSeen(ctx context.Context, id int64) error
	UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertMessageRead(ctx context.Context, arg UpsertMessageReadParams) error
}

var _ Querier = (*Queries)(nil)
