// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, avatar_url, is_admin, created_at, last_seen_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	DisplayName  string      `json:"display_name"`
	PasswordHash string      `json:"password_hash"`
	IsAdmin      pgtype.Bool `json:"is_admin"`
}

type CreateUserRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsAdmin     pgtype.Bool        `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, avatar_url, is_admin, created_at, last_seen_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, avatar_url, is_admin, created_at, last_seen_at
FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, avatar_url, is_admin, created_at, last_seen_at
FROM users ORDER BY username
`

type ListUsersRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsAdmin     pgtype.Bool        `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    avatar_url = COALESCE($3, avatar_url)
WHERE id = $1
RETURNING id, username, display_name, avatar_url, is_admin, created_at, last_seen_at
`

type UpdateUserParams struct {
	ID          int64       `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

type UpdateUserRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsAdmin     pgtype.Bool        `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
